### ISSUE TITLE
glslify potential security vulnerability via an outdated version of static-eval

### ISSUE THREAD

**Issue by mhintz** [glslify/glslify#106]
The base version of static-eval specified in the glslify package.json is affected by this security vulnerability, which was patched with static-eval version 2.0.0:

https://snyk.io/vuln/npm:static-eval:20171016

This issue is just to request that the dependency be upgraded, if that's possible. As far as I can tell, the behavior of static-eval doesn't seem to have changed that much with version 2

**Comment by mattdesl** [comment]
Fixed in latest push

**Comment by rreusser** [comment]
FWIW seems it does break cwise, though I haven't investigated why: https://github.com/scijs/cwise/pull/18

**Comment by mattdesl** [comment]
Hmm, odd.

This was passing all glslify tests but perhaps there is something we won't know about until later...

**Comment by rreusser** [comment]
Got it. If it passes, I say ship it. 🚚

Final disclaimer that I might just be wasting time by pointing out reason for concern. If it works, it works. 👍 (I get what seem like probably-spurious test failures as of a while ago in the commit history, so wasn't immediately able to check.)
