### ISSUE TITLE
ES6 module `import glsl from 'glslify'`

### ISSUE THREAD

**Issue by dy** [glslify/glslify#111]
This seems to be an issue with the latest glslify release.

```js
import glsl from 'glslify'
glsl('./file.glsl')
```

Raises 
```
file number 0:
   1|  ./file.glsl
    | ^^^
    | syntax error
```

Switching to `require('glslify')` works fine.

Related #49

**Comment by mattdesl** [comment]
Are you using babelify + browserify?

Babelify transforms your code to something much harder (if not entirely impossible?) to statically analyze:

```js
'use strict';

var _glslify = require('glslify');

var _glslify2 = _interopRequireDefault(_glslify);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

(0, _glslify2.default)('./file.glsl');'use strict';

var _glslify = require('glslify');

var _glslify2 = _interopRequireDefault(_glslify);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

(0, _glslify2.default)('./file.glsl');
```

One fix (which I should maybe add to README.md) is to translate all glslify imports to require in a babel plugin.

```js
{
  "plugins": [
    [ "import-to-require", { "modules": [ "glslify" ] } ]
  ]
}
```

See [babel-plugin-import-to-require](https://github.com/mattdesl/babel-plugin-import-to-require).

**Comment by dy** [comment]
Oh, neat transform! Thanks @mattdesl, that is better than I expected. Yep, makes point adding a note to readme.
