### ISSUE TITLE
Confusing project description

### ISSUE THREAD

**Issue by tom-leamon** [glslify/glslify#149]
Because the project description starts with a "sparkles" emoji, from Google Search it makes it appear as though the name of the project is "sparkles," especially because of the colon. Maybe put the emoji at the end instead?

![image](https://github.com/glslify/glslify/assets/18317587/a209f167-2340-4807-ad39-144f9f8a1b9f)

**Comment by chrisdickinson** [comment]
Thanks for pointing this out, fixed!
