### ISSUE TITLE
node.js support?

### ISSUE THREAD

**Issue by mikolalysenko** [glslify/glslify#8]
It should be possible to run glslify from a node.js process, possibly getting it to work with modules like headless-gl.

I think we could use fs.readFileSync as a workaround for the browserify transform and get everything running within a single node.js process.

This could also help down the road with unittesting and other features for shaders.

**Comment by vorg** [comment]
Any progress on that? I would like to do pex-glslify but need proper node support in order to make that happen.

**Comment by hughsk** [comment]
@mikolalysenko and I are gonna be catching up for a couple of weeks at the beginning of March to work on glslify/stackgl stuff, I'm going to be aiming to have the new glslify finished by then. Sorry it's taken so long :(

I think pex-glslify shaders could be created synchronously if under the hood the wrapper ignores any method calls until the shader has finished bundling: despite glslify being async it's never more than ~100ms to do so. It'd be possible to get that working right now using [glslify-bundle](https://github.com/hughsk/glslify-bundle) too :)

**Comment by vorg** [comment]
@hughsk glslify-bundle works great if you have static files. An inline source option would be still needed though. Will add an issue.

**Comment by dfcreative** [comment]
@hughsk @mikolalysenko hi! What is the status of this issue, is it still actual? There is another use-case for that https://github.com/dfcreative/gl-shader-output/issues/1.

**Comment by dfcreative** [comment]
@hughsk @yoshuawuyts @mikolalysenko @mattdesl
Since _headless-gl_ is fixed for major platforms and _glsl-transpiler_ is pretty much use-ready, with use case in _gl-shader-output_ — that feature becomes quite demanded, as far including glsl’s for processing in node is quite impossible now.
As I understand, detecting function signature is the preferrable method?

**Comment by dfcreative** [comment]
There is a workaround: [glslify-sync](https://github.com/vorg/glslify-sync), which executes glslify binary for each call. That is very slow. Also it is troublesome to include properly.
