### ISSUE TITLE
glslify with rollup?

### ISSUE THREAD

**Issue by ashleahhill** [glslify/glslify#87]
Trying to use [rollupify](https://github.com/nolanlawson/rollupify) with [glsify-bare](https://github.com/jnordberg/glslify-bare) and [babelify](https://github.com/babel/babelify). Since for rollupify I need to have the es6 modules in tact, I've been applying babelify after rollupify, which is making rollupify fail on `.glsl` files.

This hasn't worked: 

```

"browserify": {
    "transform": [
      "glslify-bare",
      ["rollupify", {
        "config": "./config/rollup.config.js"
      }],
      "babelify"
    ]
  }

```

I ran rollup on the files themselves and found that it was failing on included glsl files, so I thought something like [rollup-plugin-string](https://github.com/TrySound/rollup-plugin-string) would work

Is there a glslify plugin for rollup or has anyone gotten these two working together without one?

**Comment by mattdesl** [comment]
Any problems with just using glslfiy transform rather than glslify-bare?

**Comment by ashleahhill** [comment]
Was hoping to avoid changing all imports to glslify calls. glisify-bare transforms files based on the extension, not calls to glslify.

**Comment by mattdesl** [comment]
I've never used `glslify-bare` — generally it's not good practice to overload the require function with extra features. I think using the regular `glslify` transform will fix your issue.

It would be nice to eventually support a rollup plugin for glslify, though. :smile:

**Comment by pschroen** [comment]
bam! 😄

https://www.npmjs.com/package/rollup-plugin-glslify

Based on [rollup-plugin-string](https://github.com/TrySound/rollup-plugin-string) and automatically transforms `.vs`, `.fs`, `.glsl`, `.vert`, `.frag` files.

Works great for me!
```js
export default {
    input: 'src/Main.js',
    output: {
        file: `dist/assets/js/${project}.js`,
        format: 'es'
    },
    plugins: [
        singletons(),
        glslify(),
        eslint(),
        babel(),
        uglify({
            output: {
                preamble: `//   _  /._  _  r${pkg.version.split('.')[1]}.${project} ${timestamp()}\n//  /_|///_'/ /`
            }
        })
    ]
};
```
